name: get_device_signature
description: A Flutter plugin to retrieve the device's app signature.
version: 1.0.0
repository: https://github.com/yourusername/get_device_signature
homepage: https://github.com/yourusername/get_device_signature

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.get_device_signature
        pluginClass: GetDeviceSignaturePlugin
